server:
  port: 8000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/activiti?useUnicode=true&characterEncoding=utf8&serverTime=UTC
    username: root
    password: Gxz(001205)
  activiti:
    database-schema-update: true
    db-history-used: true
    history-level: full
  redis:
    host: 127.0.0.1
    port: 6379
project:
  manifest:
    file:
      path: classpath:/default-project.json

